# Generated by Django 4.0 on 2021-12-26 21:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_address_alter_client_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='short_description',
            field=tinymce.models.HTMLField(verbose_name='Краткое описание'),
        ),
    ]
