# Generated by Django 4.0 on 2022-01-07 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='client.client'),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phones', to='client.client'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Телефон'),
        ),
    ]
