# Generated by Django 4.0 on 2022-01-07 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_email_client_alter_email_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_emails', to='client.client'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_phones', to='client.client'),
        ),
    ]
