# Generated by Django 4.0 on 2022-01-11 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0006_alter_email_client_alter_phone_client'),
        ('project', '0002_alter_project_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_channel', models.CharField(choices=[('CH', 'Взаимодействие не выбрано'), ('RQ', 'Заявка'), ('LT', 'Письмо'), ('ST', 'Сайт'), ('INT', 'Инициатива компании')], default='CH', max_length=3, verbose_name='Канал обращения')),
                ('description', tinymce.models.HTMLField(verbose_name='Описание')),
                ('grade', models.CharField(choices=[('M5', '-5'), ('M4', '-4'), ('M3', '-3'), ('M2', '-2'), ('M1', '-1'), ('NTH', 'Нет оценки'), ('P1', '+1'), ('P2', '+2'), ('P3', '+3'), ('P4', '+4'), ('P5', '+5')], default='NTH', max_length=3, verbose_name='Оценка')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_client', to='client.client', verbose_name='Клиент')),
                ('manager', models.ManyToManyField(related_name='interaction_manager', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_project', to='project.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Взаимодействие',
                'verbose_name_plural': 'Взаимодействия',
            },
        ),
    ]
