# Generated by Django 4.0 on 2022-01-08 00:36

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0005_alter_email_client_alter_phone_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Проект')),
                ('description', tinymce.models.HTMLField(verbose_name='Описание')),
                ('date_begin', models.DateTimeField(verbose_name='Дата начала')),
                ('date_end', models.DateTimeField(verbose_name='Дата окончания')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Стоимость')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_project', to='client.client')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
